### ISSUE TITLE
请求支持P8Pro插座

### ISSUE THREAD

**Issue by Score2** [cx3Y/sunlogin#1]
共有8个插槽，每一个均能独立计量功率和开关

![0E629F2C-4FEC-4039-8ED1-8A8AD8D8C437_1_102_o](https://github.com/cx3Y/sunlogin/assets/16173457/d44e3bc5-d63a-44c3-ad8e-d3ee97cd9f85)
![EBDC9E57-6CAB-48B3-B362-54D4518D0605_1_102_o](https://github.com/cx3Y/sunlogin/assets/16173457/831403a9-0c8a-45f6-96ef-e9e76ac571bd)

**Comment by cx3Y** [comment]
你用浏览器打开这个链接
https://sl-api.oray.com/smartplugs/这里换成P8Pro的SN/electric-online
正常的话会显示类似下面这样的东西
{"vol":229238,"curr":14000,"power":1435,"result":0}

**Comment by Score2** [comment]
> 你用浏览器打开这个链接 [https://sl-api.oray.com/smartplugs/这里换成P8Pro的SN/electric-online](https://sl-api.oray.com/smartplugs/%E8%BF%99%E9%87%8C%E6%8D%A2%E6%88%90P8Pro%E7%9A%84SN/electric-online) 正常的话会显示类似下面这样的东西 {"vol":229238,"curr":14000,"power":1435,"result":0}

我试过了这个api，返回result99

刚才我尝试了一下抓包：
```
https://slapi-biz.oray.net/plug?sn=628xxxxxxxx&key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&_api=get_plug_status&time=06161428&index=0
```
然后就能获取到各个插座的信息
```
{
  "response": [
    {
      "action": 0,
      "index": 0,
      "power": 59,
      "status": 1
    },
    {
      "action": 0,
      "index": 1,
      "power": 38,
      "status": 1
    },
    {
      "action": 0,
      "index": 2,
      "power": 123,
      "status": 1
    },
    {
      "action": 0,
      "index": 3,
      "power": 0,
      "status": 0
    },
    {
      "action": 0,
      "index": 4,
      "power": 0,
      "status": 1
    },
    {
      "action": 0,
      "index": 5,
      "power": 0,
      "status": 0
    },
    {
      "action": 0,
      "index": 6,
      "power": 239,
      "status": 1
    },
    {
      "action": 0,
      "index": 7,
      "power": 0,
      "status": 0
    }
  ],
  "led": 1,
  "def_st": 2,
  "result": 0
}
```
但这api看起来不像是能直接利用的，尤其是还需要带个key

**Comment by cx3Y** [comment]
api相关参数都已经弄好了，没适配p8主要是缺少返回数据，无法绑定到entity上
get_plug_electric这个接口返回的数据应该包含P8每个口单独的电量传感器
我上传了新的你试试，这个不支持单独的电量传感器，日志打印了一些api返回的数据
![屏幕截图 2024-06-16 160823](https://github.com/cx3Y/sunlogin/assets/172144564/8008804e-7503-46e9-ad1d-b3e56b917989)

**Comment by Score2** [comment]
抱歉，我这边放假了，一段时间内接触不到p8pro了。秋季的时候我会继续跟进该issue。感谢你的适配🙏
